"""add assignment fields to sos_alerts

Revision ID: 28434aa493dd
Revises: 20260503
Create Date: 2026-05-08 10:50:45.542530

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '28434aa493dd'
down_revision = '20260503'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operator_roles_name_key', 'operator_roles', type_='unique')
    op.drop_index('ix_operator_roles_name', table_name='operator_roles')
    op.create_index(op.f('ix_operator_roles_name'), 'operator_roles', ['name'], unique=True)
    op.drop_constraint('operator_users_email_key', 'operator_users', type_='unique')
    op.drop_index('ix_operator_users_email', table_name='operator_users')
    op.create_index(op.f('ix_operator_users_email'), 'operator_users', ['email'], unique=True)
    op.add_column('sos_alerts', sa.Column('assigned_to', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('sos_alerts', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'sos_alerts', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sos_alerts', type_='foreignkey')
    op.drop_column('sos_alerts', 'assigned_at')
    op.drop_column('sos_alerts', 'assigned_to')
    op.drop_index(op.f('ix_operator_users_email'), table_name='operator_users')
    op.create_index('ix_operator_users_email', 'operator_users', ['email'], unique=False)
    op.create_unique_constraint('operator_users_email_key', 'operator_users', ['email'])
    op.drop_index(op.f('ix_operator_roles_name'), table_name='operator_roles')
    op.create_index('ix_operator_roles_name', 'operator_roles', ['name'], unique=False)
    op.create_unique_constraint('operator_roles_name_key', 'operator_roles', ['name'])
    # ### end Alembic commands ###
