"""new database changes

Revision ID: 38b8c77371c1
Revises: 8509bce778b2
Create Date: 2026-05-19 18:26:17.866224

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '38b8c77371c1'
down_revision = '8509bce778b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_users', sa.Column('setup_completed', sa.Boolean(), nullable=True))
    op.execute("UPDATE operator_users SET setup_completed = FALSE")
    op.alter_column('operator_users', 'setup_completed', nullable=False)
    op.create_index(op.f('ix_operator_users_setup_completed'), 'operator_users', ['setup_completed'], unique=False)
    op.add_column('support_centers', sa.Column('operator_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_support_centers_operator_id'), 'support_centers', ['operator_id'], unique=False)
    op.create_foreign_key(None, 'support_centers', 'operator_users', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_centers', type_='foreignkey')
    op.drop_index(op.f('ix_support_centers_operator_id'), table_name='support_centers')
    op.drop_column('support_centers', 'operator_id')
    op.drop_index(op.f('ix_operator_users_setup_completed'), table_name='operator_users')
    op.drop_column('operator_users', 'setup_completed')
    # ### end Alembic commands ###
