"""add assignment fields to sos_alerts

Revision ID: 8509bce778b2
Revises: 28434aa493dd
Create Date: 2026-05-08 11:19:18.866283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8509bce778b2'
down_revision = '28434aa493dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sos_alerts_resolved_by_fkey', 'sos_alerts', type_='foreignkey')
    op.drop_constraint('sos_alerts_assigned_to_fkey', 'sos_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'sos_alerts', 'operator_users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sos_alerts', 'operator_users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sos_alerts', type_='foreignkey')
    op.drop_constraint(None, 'sos_alerts', type_='foreignkey')
    op.create_foreign_key('sos_alerts_assigned_to_fkey', 'sos_alerts', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('sos_alerts_resolved_by_fkey', 'sos_alerts', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
