"""initial migrations

Revision ID: a2f8490ce0cd
Revises: 
Create Date: 2026-05-01 09:58:37.116668

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'a2f8490ce0cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('otp_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_expires_at'), 'otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone_number'), 'otp_codes', ['phone_number'], unique=False)
    op.create_table('support_centers',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('center_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('category_tags', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geo_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('phone_primary', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('phone_emergency', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_24_7', sa.Boolean(), nullable=False),
    sa.Column('operating_hours', sa.Text(), nullable=True),
    sa.Column('languages_supported', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('provides_medical', sa.Boolean(), nullable=False),
    sa.Column('provides_legal', sa.Boolean(), nullable=False),
    sa.Column('provides_shelter', sa.Boolean(), nullable=False),
    sa.Column('provides_counseling', sa.Boolean(), nullable=False),
    sa.Column('provides_emergency_response', sa.Boolean(), nullable=False),
    sa.Column('provides_anonymous_support', sa.Boolean(), nullable=False),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=False),
    sa.Column('gender_specific', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('age_restrictions', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('data_quality_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('temporarily_closed', sa.Boolean(), nullable=False),
    sa.Column('closure_reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_support_centers_geo_location ON support_centers USING gist (geo_location)")
    op.create_index(op.f('ix_support_centers_center_type'), 'support_centers', ['center_type'], unique=False)
    op.create_index(op.f('ix_support_centers_city'), 'support_centers', ['city'], unique=False)
    op.create_index(op.f('ix_support_centers_country'), 'support_centers', ['country'], unique=False)
    op.create_index(op.f('ix_support_centers_is_24_7'), 'support_centers', ['is_24_7'], unique=False)
    op.create_index(op.f('ix_support_centers_is_active'), 'support_centers', ['is_active'], unique=False)
    op.create_index(op.f('ix_support_centers_is_verified'), 'support_centers', ['is_verified'], unique=False)
    op.create_index(op.f('ix_support_centers_latitude'), 'support_centers', ['latitude'], unique=False)
    op.create_index(op.f('ix_support_centers_longitude'), 'support_centers', ['longitude'], unique=False)
    op.create_table('training_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('color_code', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_training_categories_is_active'), 'training_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_training_categories_slug'), 'training_categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('language_preference', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('emergency_message_template', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_anonymous'), 'users', ['is_anonymous'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('anonymous_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('device_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_sessions_device_fingerprint'), 'anonymous_sessions', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_anonymous_sessions_session_token'), 'anonymous_sessions', ['session_token'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('conversation_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('support_center_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('support_ticket_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encryption_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['support_center_id'], ['support_centers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_conversation_type'), 'conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_table('incident_reports',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('report_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_latitude', sa.Float(), nullable=True),
    sa.Column('incident_longitude', sa.Float(), nullable=True),
    sa.Column('incident_address', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('reporter_age_range', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('reporter_gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('description_encrypted', sa.Text(), nullable=True),
    sa.Column('encryption_metadata', sa.JSON(), nullable=True),
    sa.Column('follow_up_preference', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('contact_email_encrypted', sa.Text(), nullable=True),
    sa.Column('contact_phone_encrypted', sa.Text(), nullable=True),
    sa.Column('submitted_from_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('submitted_from_device', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('offline_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_is_anonymous'), 'incident_reports', ['is_anonymous'], unique=False)
    op.create_index(op.f('ix_incident_reports_offline_id'), 'incident_reports', ['offline_id'], unique=False)
    op.create_index(op.f('ix_incident_reports_report_number'), 'incident_reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_incident_reports_report_type'), 'incident_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_incident_reports_status'), 'incident_reports', ['status'], unique=False)
    op.create_index(op.f('ix_incident_reports_user_id'), 'incident_reports', ['user_id'], unique=False)
    op.create_table('sos_alerts',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('initial_latitude', sa.Float(), nullable=False),
    sa.Column('initial_longitude', sa.Float(), nullable=False),
    sa.Column('initial_accuracy', sa.Float(), nullable=True),
    sa.Column('initial_address', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('triggered_by_device_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('contacts_notified', sa.Integer(), nullable=False),
    sa.Column('centers_notified', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('offline_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_alerts_created_at'), 'sos_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_sos_alerts_offline_id'), 'sos_alerts', ['offline_id'], unique=False)
    op.create_index(op.f('ix_sos_alerts_status'), 'sos_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_sos_alerts_user_id'), 'sos_alerts', ['user_id'], unique=False)
    op.create_table('training_lessons',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_blocks', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('completion_count', sa.Integer(), nullable=False),
    sa.Column('rating_average', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('requires_login', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('related_lesson_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['training_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_lessons_category_id'), 'training_lessons', ['category_id'], unique=False)
    op.create_index(op.f('ix_training_lessons_is_active'), 'training_lessons', ['is_active'], unique=False)
    op.create_index(op.f('ix_training_lessons_slug'), 'training_lessons', ['slug'], unique=False)
    op.create_table('trusted_contacts',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('notify_push', sa.Boolean(), nullable=False),
    sa.Column('notify_call', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_contacts_user_id'), 'trusted_contacts', ['user_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('notifications_muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('key_exchange_complete', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='unique_conversation_participant')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.create_table('evidence_files',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('report_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('storage_bucket', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('file_encryption_key_encrypted', sa.Text(), nullable=True),
    sa.Column('encryption_iv', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('encryption_metadata', sa.JSON(), nullable=True),
    sa.Column('file_hash_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('file_hash_original', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_encrypted', sa.Boolean(), nullable=False),
    sa.Column('extracted_metadata', sa.JSON(), nullable=True),
    sa.Column('has_gps_metadata', sa.Boolean(), nullable=False),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('virus_scan_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_files_file_type'), 'evidence_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_evidence_files_offline_id'), 'evidence_files', ['offline_id'], unique=False)
    op.create_index(op.f('ix_evidence_files_report_id'), 'evidence_files', ['report_id'], unique=False)
    op.create_table('location_pings',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('alert_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('network_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('offline_sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['sos_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_pings_alert_id'), 'location_pings', ['alert_id'], unique=False)
    op.create_index(op.f('ix_location_pings_recorded_at'), 'location_pings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_location_pings_user_id'), 'location_pings', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('reply_to_message_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('encrypted_content', sa.Text(), nullable=True),
    sa.Column('encryption_metadata', sa.Text(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('attachment_encrypted', sa.Boolean(), nullable=False),
    sa.Column('attachment_storage_path', sa.Text(), nullable=True),
    sa.Column('attachment_metadata_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('server_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_location_pings_user_id'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_recorded_at'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_alert_id'), table_name='location_pings')
    op.drop_table('location_pings')
    op.drop_index(op.f('ix_evidence_files_report_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_offline_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_file_type'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_trusted_contacts_user_id'), table_name='trusted_contacts')
    op.drop_table('trusted_contacts')
    op.drop_index(op.f('ix_training_lessons_slug'), table_name='training_lessons')
    op.drop_index(op.f('ix_training_lessons_is_active'), table_name='training_lessons')
    op.drop_index(op.f('ix_training_lessons_category_id'), table_name='training_lessons')
    op.drop_table('training_lessons')
    op.drop_index(op.f('ix_sos_alerts_user_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_status'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_offline_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_created_at'), table_name='sos_alerts')
    op.drop_table('sos_alerts')
    op.drop_index(op.f('ix_incident_reports_user_id'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_status'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_report_type'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_report_number'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_offline_id'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_is_anonymous'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_type'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_anonymous_sessions_session_token'), table_name='anonymous_sessions')
    op.drop_index(op.f('ix_anonymous_sessions_device_fingerprint'), table_name='anonymous_sessions')
    op.drop_table('anonymous_sessions')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_anonymous'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_categories_slug'), table_name='training_categories')
    op.drop_index(op.f('ix_training_categories_is_active'), table_name='training_categories')
    op.drop_table('training_categories')
    op.drop_index(op.f('ix_support_centers_longitude'), table_name='support_centers')
    op.drop_index(op.f('ix_support_centers_latitude'), table_name='support_centers')
    op.drop_index(op.f('ix_support_centers_is_verified'), table_name='support_centers')
    op.drop_index(op.f('ix_support_centers_is_active'), table_name='support_centers')
    op.drop_index(op.f('ix_support_centers_is_24_7'), table_name='support_centers')
    op.drop_index(op.f('ix_support_centers_country'), table_name='support_centers')
    op.drop_index(op.f('ix_support_centers_city'), table_name='support_centers')
    op.drop_index(op.f('ix_support_centers_center_type'), table_name='support_centers')
    op.drop_index('idx_support_centers_geo_location', table_name='support_centers', postgresql_using='gist')
    op.drop_table('support_centers')
    op.drop_index(op.f('ix_otp_codes_phone_number'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_expires_at'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
